package com.example.loginMana.config;

import com.example.loginMana.entities.UserEntity;
import com.example.loginMana.repositories.UserRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Configuration;

import java.util.Arrays;

@Configuration
@RequiredArgsConstructor
public class Instantiation implements CommandLineRunner {

    private final UserRepository userRepository;

    @Override
    public void run(String... args0) throws Exception {
        userRepository.deleteAll();

        UserEntity user1 = new UserEntity(
                null,                       // id (will be generated by the database)
                "Alice",                    // name
                "Smith",                    // lastName
                "alice_admin",              // userName (@NonNull)
                "adminPass123",             // password (@NonNull)
                "ADMIN",                    // role
                "alice.smith@example.com",  // email (@NonNull)
                "LOCAL",                    // provider
                null,                       // providerId
                null                        // profilePicture
        );

        UserEntity user2 = new UserEntity(
                null,
                "Bob",
                "Johnson",
                "bob_user",                 // userName (@NonNull)
                "userPass456",              // password (@NonNull)
                "USER",                     // role
                "bob.johnson@example.com",  // email (@NonNull)
                "LOCAL",
                null,
                null
        );

        userRepository.saveAll(Arrays.asList(user1, user2));

        System.out.println("Mock users populated successfully!");

    }

}
